image:
  repository: ghcr.io/jef/zap2xml
  pullPolicy: IfNotPresent
  tag: v2.2.0

resources:
  limits:
    cpu: 500m
    memory: 256Mi

zap2xmlConfig:
  outputFile: /xmltv/xmltv.xml
  lineupId: USA-OTA78735
  timespan: 168
  postalCode: "78735"
  sleepTime: 21600
  additionalEnvs: []

zap2xmlRunAs:
  user: 568
  group: 568

zap2xmlStorage:
  xmltv:
    type: ixVolume
    ixVolumeConfig:
      datasetName: xmltv
  additionalStorages: []
