image:
  repository: ghcr.io/haveagitgat/tdarr
  pullPolicy: IfNotPresent
  tag: 2.45.01

tdarrConfig:
  serverIP: 0.0.0.0
  webUIPort: 8265
  serverPort: 8266
  internalNode: true
  nodeName: "TestNode"
  ffmpegVersion: 7
  additionalEnvs: []

tdarrID:
  user: 568
  group: 568

tdarrNetwork:
  webPort: 30265
  serverPort: 30266

tdarrStorage:
  server:
    type: hostPath
    mountPath: /app/server
    hostPathConfig:
      hostPath: /tmp/test-server
  configs:
    type: hostPath
    mountPath: /app/configs
    hostPathConfig:
      hostPath: /tmp/test-configs
  logs:
    type: hostPath
    mountPath: /app/logs
    hostPathConfig:
      hostPath: /tmp/test-logs
  temp:
    type: hostPath
    mountPath: /temp
    hostPathConfig:
      hostPath: /tmp/test-temp
  mediaMovies:
    enabled: true
    type: hostPath
    mountPath: /media/Movies
    hostPathConfig:
      hostPath: /mnt/media/Movies
  mediaTV:
    enabled: true
    type: hostPath
    mountPath: /media/TV
    hostPathConfig:
      hostPath: /mnt/media/TV
  transcodeMovies:
    enabled: true
    type: hostPath
    mountPath: /transcode/Movies
    hostPathConfig:
      hostPath: /mnt/transcode/Movies
  transcodeTV:
    enabled: true
    type: hostPath
    mountPath: /transcode/TV
    hostPathConfig:
      hostPath: /mnt/transcode/TV
  pluginsLocal:
    enabled: false
  pluginsFlow:
    enabled: false
  pluginsFlowTemplates:
    enabled: false
  additionalStorages: []

tdarrGPU: {}

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

TZ: America/New_York
